#!/bin/sh

# TODO dynamic folder name
ln -sfv ~/.dotfiles/.vimrc ~/.vimrc
ln -sfv ~/.dotfiles/.vimrc.bundles ~/.vimrc.bundles
ln -sfv ~/.dotfiles/.agignore ~/.agignore
ln -sfv ~/.dotfiles/.aliases ~/.aliases
ln -sfv ~/.dotfiles/.ctags ~/.ctags
ln -sfv ~/.dotfiles/.gitconfig ~/.gitconfig
ln -sfv ~/.dotfiles/.gitignore_global ~/.gitignore_global
ln -sfv ~/.dotfiles/.tmux.conf ~/.tmux.conf
ln -sfv ~/.dotfiles/.tmux.conf ~/.tmux.conf
ln -sfv ~/.dotfiles/.bashrc ~/.bashrc
