#!/bin/sh

# TODO install vim-plug here

DOTFILES="$HOME/.dotfiles"

if [ "$1" != "" ]; then
    DOTFILES=$1
fi

# TODO get all files dynamically
ln -sfv $DOTFILES/.vimrc ~/.vimrc
ln -sfv $DOTFILES/.pluginconfig.vim ~/.pluginconfig.vim
ln -sfv $DOTFILES/.agignore ~/.agignore
ln -sfv $DOTFILES/.aliases ~/.aliases
ln -sfv $DOTFILES/.ctags ~/.ctags
ln -sfv $DOTFILES/.gitconfig ~/.gitconfig
ln -sfv $DOTFILES/.gitignore_global ~/.gitignore_global
ln -sfv $DOTFILES/.tmux.conf ~/.tmux.conf
ln -sfv $DOTFILES/.bashrc ~/.bashrc
ln -sfv $DOTFILES/.editorconfig ~/.editorconfig
