#!/bin/sh

# TODO get file names dynamically
rm ~/.vimrc
rm ~/.vimrc.bundles
rm ~/.agignore
rm ~/.aliases
rm ~/.ctags
rm ~/.gitconfig
rm ~/.gitignore_global
rm ~/.tmux.conf
rm ~/.bashrc
rm ~/.editorconfig
