#!/bin/sh

remove_file () {
    if [ ! -e "$1" ]; then
        echo "File $1 doesn't exists\n"
    else
        rm "$1"
    fi
}

# TODO get file names dynamically
remove_file ~/.vimrc
remove_file ~/.pluginconfig.vim
remove_file ~/.agignore
remove_file ~/.aliases
remove_file ~/.ctags
remove_file ~/.gitconfig
remove_file ~/.gitignore_global
remove_file ~/.tmux.conf
# remove_file ~/.bashrc
remove_file ~/.editorconfig

if [ `uname` = "Linux" ]; then
    remove_file "$HOME/.config/Code/User/settings.json"
elif [ `uname` = "Darwin" ]; then
    remove_file "$HOME/Library/Application\\ Support/Code/User/settings.json"
fi
