# https://sw.kovidgoyal.net/kitty/conf/

font_family Lilex Nerd Font Mono
font_size 14
macos_titlebar_color background
macos_option_as_alt yes
disable_ligatures always

include ./themes/tokyonight_night.conf
