add_newline = false

[custom.tmux]
description = "Indicator that shows up if currently in a tmux session"
command = """ if tmux list-panes -F '#F' | grep -q Z; then echo '■ ■'; else echo '■'; fi """
when = """ [[ -n $TMUX ]] && exit 0 """
