#!/bin/bash
nvim_in_current=false
while read active cmd; do
  if [ "$active" = "1" ] && [ "$cmd" = "nvim" ]; then
    nvim_in_current=true
    break
  fi
done < <(tmux list-panes -F "#{pane_active} #{pane_current_command}")

if $nvim_in_current; then
  tmux set -g status off
else
  tmux set -g status on
fi

