# (Windows)
# [terminal]
# shell = { program = "C:\\Windows\\System32\\wsl.exe", args = ["--cd ~"] }

[env]
TERM="xterm-256color"
LANG="en_US.UTF-8"
LC_ALL="en_US.UTF-8"

[window]
# (Windows/Linux)
# decorations = "None"
# startup_mode = "Maximized"

# (MacOS)
option_as_alt = "Both"

[font]
size = 14
# size = 11.5 # Monaspice

# offset = { y = 2, x = 1 } # for BlexMono
# offset = { y = 3 } # for Monaspice


# normal = { family = "Zed Mono", style = "Extended" }
# normal = { family = "ZedMono Nerd Font", style = "Extended" }
# normal = { family = "JetBrainsMonoNL Nerd Font Mono", style = "Regular" }
# normal = { family = "MonaspiceNe Nerd Font Mono", style = "Regular" }
# normal = { family = "MonaspiceAr Nerd Font Mono", style = "Regular" }
# normal = { family = "MonaspiceXe Nerd Font Mono", style = "Regular" }
# normal = { family = "MonaspiceRn Nerd Font Mono", style = "Regular" }
# normal = { family = "Hasklug Nerd Font Mono", style = "Regular" }
# normal = { family = "0xProto Nerd Font Mono", style = "Regular" }
# normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
# normal = { family = "CaskaydiaCove Nerd Font Mono", style = "Regular" }
# normal = { family = "IntoneMono Nerd Font Mono", style = "Regular" }
# normal = { family = "CommitMono Nerd Font", style = "Regular" }

normal = { family = "BlexMono Nerd Font", style = "Text" }
italic = { family = "BlexMono Nerd Font", style = "Text Italic" }

[keyboard]
bindings = [
{ key = "Space", mods = "Control", chars = "\u0000" }
]

# Colors (Tokyo Night)

# Source https//github.com/zatchheems/tokyo-night-alacritty-theme

# Default colors
[colors.primary]
background = '#1a1b26'
foreground = '#a9b1d6'


# Normal colors

[colors.normal]
black   = '#32344a'
red     = '#f7768e'

green   = '#9ece6a'
yellow  = '#e0af68'
blue    = '#7aa2f7'
magenta = '#ad8ee6'

cyan    = '#449dab'
white   = '#787c99'


# Bright colors
[colors.bright]
black   = '#444b6a'
red     = '#ff7a93'
green   = '#b9f27c'
yellow  = '#ff9e64'
blue    = '#7da6ff'
magenta = '#bb9af7'

cyan    = '#0db9d7'

white   = '#acb0d0'

# # Iceberg Theme ===================

# [colors.primary]
# # background = "#16171E"
# background = "#161821"
# foreground = "#D1D2D3"
#
# [colors.cursor]
#
# text= "#FEFFFF"
# cursor= "#c7c7c7"
#
# # Normal colors
# [colors.normal]
#
# black= "#161821"

# red= "#E68E8E"
# green= "#83AC8E"
# yellow= "#F5B78A"
# blue= "#9BB8DC"
# magenta= "#BAACE2"
# cyan= "#00C5C7"
# white= "#C7C7C7"
#
# [colors.dim]
#
# black= "#161821"
# red= "#E68E8E"
# green= "#83AC8E"

# yellow= "#F5B78A"
# blue= "#9BB8DC"
# magenta= "#BAACE2"
# cyan= "#00C5C7"
# white= "#C7C7C7"
#
# # Bright colors
# [colors.bright]

# black= "#676767"
# red= "#FF6D67"
# green= "#5FF967"
# yellow= "#FEFB67"
# blue= "#6871FF"
# magenta= "#FF76FF"
# cyan= "#5FFDFF"
# white= "#FEFFFF"
# # ==================== end Iceberg theme

