# https://alacritty.org/config-alacritty.html

[general]
import = ["~/dotfiles/home/.config/alacritty/onedark.toml"]

[window]
# (MacOS)
option_as_alt = "Both"
startup_mode = "Maximized"

dynamic_padding = true

[font]
size = 13.5
# normal = { family = "IoskeleyMono Nerd Font", style = "Regular" }
# italic = { family = "IoskeleyMono Nerd Font", style = "Italic" }
normal = { family = "Lilex Nerd Font Mono", style = "Regular" }
italic = { family = "Lilex Nerd Font Mono", style = "Italic" }

[keyboard]
bindings = [
{ key = "Space", mods = "Control", chars = "\u0000" },
{ key = "Key6", mods = "Control", chars = "\u001e" },
# (MacOS)
{ key = "F", mods = "Command|Control", action = "ToggleSimpleFullscreen" }
]
