[general]
import = ["nightfox.toml"]

[window]
# (MacOS)
option_as_alt = "Both"

[font]
size = 13.5
normal = { family = "Lilex", style = "Regular" }

[keyboard]
bindings = [
{ key = "Space", mods = "Control", chars = "\u0000" }
]
