[general]
import = ["~/dotfiles/home/.config/alacritty/nvim_dark.toml"]

[window]
# (MacOS)
option_as_alt = "Both"
startup_mode = "Maximized"

dynamic_padding = true

[font]
size = 18
normal = { family = "Ioskeley Mono", style = "Regular" }
# offset = { x = 0, y = 2 }
# glyph_offset = { x = 0, y = 1 }

[keyboard]
bindings = [
{ key = "Space", mods = "Control", chars = "\u0000" },
{ key = "Key6", mods = "Control", chars = "\u001e" },
# (MacOS)
{ key = "F", mods = "Command|Control", action = "ToggleSimpleFullscreen" }
]
