[colors.primary]
background = "#14161b"
foreground = "#e0e2ea"

[colors.normal]
black   = "#07080d" # NvimDarkGrey1
red     = "#ffc0b9" # NvimLightRed
green   = "#b3f6c0" # NvimLightGreen
yellow  = "#fce094" # NvimLightYellow
blue    = "#a6dbff" # NvimLightBlue
magenta = "#ffcaff" # approximated
cyan    = "#8cf8f7" # NvimLightCyan
white   = "#e0e2ea" # NvimLightGrey2

[colors.bright]
black   = "#4f5258" # NvimDarkGrey4
red     = "#ffc0b9"
green   = "#b3f6c0"
yellow  = "#fce094"
blue    = "#a6dbff"
magenta = "#ffcaff"
cyan    = "#8cf8f7"
white   = "#ffffff"

[colors.cursor]
text = "#14161b"
cursor = "#e0e2ea"

[colors.selection]
text = "#e0e2ea"
background = "#4f5258"
